name: druto_seba_driver
description: A new Flutter project.
 
publish_to: 'none'  
 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
 
dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.2
  get:
  hexcolor:
  # google_fonts:
  ionicons: ^0.2.2
  # dotted_border: 
  pinput: ^2.2.10
  google_fonts: ^4.0.1
  dotted_border: ^2.0.0+3
  image_picker: ^1.0.7
  bottom_picker: ^2.4.0
  intl: ^0.18.1
  google_maps_flutter: ^2.0.7
  google_maps_webservice: ^0.0.15
  flutter_google_places: ^0.3.0
  flutter_tts: ^3.0.0
  location: ^5.0.3
  flutter_polyline_points: ^1.0.0
  flutter_spinkit: ^5.2.0
  flutter_local_notifications: ^8.2.0
  vibration: ^1.7.2
  flutter_snake_navigationbar: ^0.6.1
  get_storage: ^2.1.1
  cached_network_image: ^3.3.1
  lottie: ^3.0.0

  #network
  http: ^0.13.6
  month_year_picker: ^0.3.0+1
  url_launcher: ^6.0.6




 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  change_app_package_name: ^1.1.0
 
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon-logo.png"
 
flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/icon/
    - assets/lottie/
