// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR6WIMozwsinFuThA4iEgXYZKeysUWGfo',
    appId: '1:826145358020:web:4c9b5e28655453258a8991',
    messagingSenderId: '826145358020',
    projectId: 'rantal-9d9a7',
    authDomain: 'rantal-9d9a7.firebaseapp.com',
    storageBucket: 'rantal-9d9a7.appspot.com',
    measurementId: 'G-T41VY8VVZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx_IYps3bJZmHdt_W5JnlojFxGAm9Gry4',
    appId: '1:826145358020:android:88672ffc5310d8b18a8991',
    messagingSenderId: '826145358020',
    projectId: 'rantal-9d9a7',
    storageBucket: 'rantal-9d9a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrKwiytU9wb_npVwB1rOhLhPQnrOpei1g',
    appId: '1:826145358020:ios:588c7fd5c52e277e8a8991',
    messagingSenderId: '826145358020',
    projectId: 'rantal-9d9a7',
    storageBucket: 'rantal-9d9a7.appspot.com',
    iosBundleId: 'com.example.drutoShebaDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrKwiytU9wb_npVwB1rOhLhPQnrOpei1g',
    appId: '1:826145358020:ios:588c7fd5c52e277e8a8991',
    messagingSenderId: '826145358020',
    projectId: 'rantal-9d9a7',
    storageBucket: 'rantal-9d9a7.appspot.com',
    iosBundleId: 'com.example.drutoShebaDriver',
  );
}
